services:
  # # UNCOMMENT THIS TO USE IN DEVELOPMENT
  # dev-db:
  #   image: postgres:latest
  #   env_file:
  #     - .env.development
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - dev-data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    image: enigma
    ports:
      - "3000:3000"

volumes:
  dev-data:
  data:
