import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import * as Tooltip from "@radix-ui/react-tooltip";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Enigma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Tooltip.Provider delayDuration={200}>{children}</Tooltip.Provider>
      </body>
    </html>
  );
}
