services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    image: enigma
    ports:
      - "3000:3000"
    volumes:
      - D:/file-storage:/app/uploads # MODIFY THIS TO YOUR PATH

volumes:
  data:
  file-storage:
